"""init schema

Revision ID: a8425e13d75c
Revises: 
Create Date: 2026-04-23 01:39:11.191246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8425e13d75c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_note_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), server_default=sa.text("'markdown'"), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb_build_object('x', 0, 'y', 0)"), nullable=False),
    sa.Column('size', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb_build_object('width', 200, 'height', 200)"), nullable=False),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb_build_object('color', 'yellow')"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('checkpoint_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_parent_note_id'), 'notes', ['parent_note_id'], unique=False)
    op.create_index('ix_notes_user_id', 'notes', ['user_id'], unique=False)
    op.create_index('ix_notes_user_id_updated_at', 'notes', ['user_id', 'updated_at'], unique=False)
    op.create_index('ix_notes_user_parent_updated_at', 'notes', ['user_id', 'parent_note_id', 'updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('authorization_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.String(length=1000), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_codes_code_hash'), 'authorization_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_authorization_codes_user_id'), 'authorization_codes', ['user_id'], unique=False)
    op.create_table('calendar_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', name='calendarprovider'), nullable=False),
    sa.Column('provider_calendar_id', sa.String(length=255), server_default=sa.text("'primary'"), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('granted_scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_resource_id', sa.String(length=255), nullable=True),
    sa.Column('channel_expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_calendar_id', name='uq_calendar_connections_user_provider_calendar')
    )
    op.create_index('ix_calendar_connections_provider_last_synced_at', 'calendar_connections', ['provider', 'last_synced_at'], unique=False)
    op.create_index(op.f('ix_calendar_connections_user_id'), 'calendar_connections', ['user_id'], unique=False)
    op.create_table('note_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('patch', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('patch_format', sa.String(length=32), server_default=sa.text("'text_diff'"), nullable=False),
    sa.Column('content_length', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'version', name='uq_note_revisions_note_version')
    )
    op.create_index(op.f('ix_note_revisions_note_id'), 'note_revisions', ['note_id'], unique=False)
    op.create_index('ix_note_revisions_note_id_version', 'note_revisions', ['note_id', 'version'], unique=False)
    op.create_index(op.f('ix_note_revisions_user_id'), 'note_revisions', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', name='calendarprovider'), nullable=False),
    sa.Column('state_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_states_provider_expires_at', 'oauth_states', ['provider', 'expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_states_state_hash'), 'oauth_states', ['state_hash'], unique=True)
    op.create_index(op.f('ix_oauth_states_user_id'), 'oauth_states', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('CLASS', 'DEADLINE', 'EXAM', 'PERSONAL', name='scheduletype'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'uploading', 'completed', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('upload_id', sa.String(length=255), nullable=False),
    sa.Column('total_parts', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_object_key'), 'uploads', ['object_key'], unique=True)
    op.create_index(op.f('ix_uploads_upload_id'), 'uploads', ['upload_id'], unique=True)
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_index('ix_uploads_user_status_created_at', 'uploads', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('uploaded_video', 'screen_recording', 'live_session', name='assettype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', 'completed', 'archived', name='assetstatus'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_upload_id', sa.UUID(), nullable=True),
    sa.Column('source_object_key', sa.String(length=1024), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('frame_rate', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_checksum_sha256'), 'assets', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_assets_source_upload_id'), 'assets', ['source_upload_id'], unique=False)
    op.create_index('ix_assets_user_created', 'assets', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_index('ix_assets_user_status', 'assets', ['user_id', 'status'], unique=False)
    op.create_table('schedule_external_maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', name='calendarprovider'), nullable=False),
    sa.Column('provider_calendar_id', sa.String(length=255), server_default=sa.text("'primary'"), nullable=False),
    sa.Column('provider_event_id', sa.String(length=1024), nullable=False),
    sa.Column('provider_etag', sa.String(length=255), nullable=True),
    sa.Column('provider_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_source', sa.Enum('INTERNAL', 'PROVIDER', name='syncsource'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted_remote', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_calendar_id', 'provider_event_id', name='uq_schedule_external_maps_provider_event'),
    sa.UniqueConstraint('schedule_id', 'provider', name='uq_schedule_external_maps_schedule_provider')
    )
    op.create_index('ix_schedule_external_maps_provider_event_id', 'schedule_external_maps', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_schedule_external_maps_schedule_id'), 'schedule_external_maps', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_external_maps_user_id'), 'schedule_external_maps', ['user_id'], unique=False)
    op.create_index('ix_schedule_external_maps_user_provider', 'schedule_external_maps', ['user_id', 'provider'], unique=False)
    op.create_table('upload_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_record_id', sa.UUID(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_record_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_record_id', 'part_number', name='uq_upload_parts_upload_part_number')
    )
    op.create_index('ix_upload_parts_upload_part_number', 'upload_parts', ['upload_record_id', 'part_number'], unique=False)
    op.create_index(op.f('ix_upload_parts_upload_record_id'), 'upload_parts', ['upload_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_parts_upload_record_id'), table_name='upload_parts')
    op.drop_index('ix_upload_parts_upload_part_number', table_name='upload_parts')
    op.drop_table('upload_parts')
    op.drop_index('ix_schedule_external_maps_user_provider', table_name='schedule_external_maps')
    op.drop_index(op.f('ix_schedule_external_maps_user_id'), table_name='schedule_external_maps')
    op.drop_index(op.f('ix_schedule_external_maps_schedule_id'), table_name='schedule_external_maps')
    op.drop_index('ix_schedule_external_maps_provider_event_id', table_name='schedule_external_maps')
    op.drop_table('schedule_external_maps')
    op.drop_index('ix_assets_user_status', table_name='assets')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index('ix_assets_user_created', table_name='assets')
    op.drop_index(op.f('ix_assets_source_upload_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_checksum_sha256'), table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_uploads_user_status_created_at', table_name='uploads')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_upload_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_object_key'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_oauth_states_user_id'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_state_hash'), table_name='oauth_states')
    op.drop_index('ix_oauth_states_provider_expires_at', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_note_revisions_user_id'), table_name='note_revisions')
    op.drop_index('ix_note_revisions_note_id_version', table_name='note_revisions')
    op.drop_index(op.f('ix_note_revisions_note_id'), table_name='note_revisions')
    op.drop_table('note_revisions')
    op.drop_index(op.f('ix_calendar_connections_user_id'), table_name='calendar_connections')
    op.drop_index('ix_calendar_connections_provider_last_synced_at', table_name='calendar_connections')
    op.drop_table('calendar_connections')
    op.drop_index(op.f('ix_authorization_codes_user_id'), table_name='authorization_codes')
    op.drop_index(op.f('ix_authorization_codes_code_hash'), table_name='authorization_codes')
    op.drop_table('authorization_codes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_notes_user_parent_updated_at', table_name='notes')
    op.drop_index('ix_notes_user_id_updated_at', table_name='notes')
    op.drop_index('ix_notes_user_id', table_name='notes')
    op.drop_index(op.f('ix_notes_parent_note_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
